services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"