// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DockerRepository is an autogenerated mock type for the DockerRepository type
type DockerRepository struct {
	mock.Mock
}

// GetExists provides a mock function with given fields: ctx, registry, _a2, tag, username, password
func (_m *DockerRepository) GetExists(ctx context.Context, registry string, _a2 string, tag string, username string, password string) (bool, error) {
	ret := _m.Called(ctx, registry, _a2, tag, username, password)

	if len(ret) == 0 {
		panic("no return value specified for GetExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (bool, error)); ok {
		return rf(ctx, registry, _a2, tag, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) bool); ok {
		r0 = rf(ctx, registry, _a2, tag, username, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = rf(ctx, registry, _a2, tag, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDockerRepository creates a new instance of DockerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDockerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DockerRepository {
	mock := &DockerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
